// Serialize an AnalysisResult to Markdown — used for the Download button and the
// emailed copy. Numbers come from our own data, not the model.

import type { AnalysisResult, Campaign } from "./types";

function pct(n: number): string {
  return `${n}%`;
}

function campaignRow(c: Campaign): string {
  const date = c.sendAt ? c.sendAt.slice(0, 10) : "—";
  const rev = c.revenue != null ? ` | $${c.revenue}` : "";
  return `| ${c.subject.replace(/\|/g, "/")} | ${date} | ${c.stats.recipients} | ${pct(
    c.stats.open_rate,
  )} | ${pct(c.stats.click_rate)} | ${c.stats.unsubscribes} | ${c.score}${rev} |`;
}

export function reportToMarkdown(r: AnalysisResult): string {
  const lines: string[] = [];
  const L = (s = "") => lines.push(s);

  L(`# Success Signal Analysis`);
  L();
  L(`_Account: ${r.account.name} · ${r.campaigns.length} campaigns analyzed_`);
  L();

  L(`## Executive Summary`);
  for (const b of r.report.executive_summary) L(`- ${b}`);
  L();

  L(`## Your Success Goal`);
  L(r.report.success_goal);
  L(`\n_Scored by ${r.scoreMethod}._`);
  L();

  L(`## Campaigns Analyzed`);
  const revCol = r.revenueAvailable ? " Revenue |" : "";
  const revSep = r.revenueAvailable ? " --- |" : "";
  L(`| Subject | Sent | Recipients | Open | Click | Unsubs | Score |${revCol}`);
  L(`| --- | --- | --- | --- | --- | --- | --- |${revSep}`);
  for (const c of r.campaigns) L(campaignRow(c));
  L();

  L(`## Top Performers`);
  for (const c of r.top) L(`- **${c.subject}** — score ${c.score}`);
  L();
  L(`## Bottom Performers`);
  for (const c of r.bottom) L(`- ${c.subject} — score ${c.score}`);
  L();

  L(`## Success Signals Detected`);
  for (const s of r.report.signals) {
    L(`### ${s.name}`);
    L(`**Evidence**`);
    for (const e of s.evidence) L(`- ${e}`);
    L(`\n**Why this may matter** — ${s.why_it_matters}`);
    L(`\n**Related marketing principle** — ${s.related_principle}`);
    L(`\n**Recommended experiment** — ${s.recommended_experiment}`);
    L(`\n**Confidence: ${s.confidence}** — ${s.confidence_reason}`);
    L();
  }

  L(`## What To Repeat`);
  for (const b of r.report.what_to_repeat) L(`- ${b}`);
  L();
  L(`## What To Stop Doing`);
  for (const b of r.report.what_to_stop) L(`- ${b}`);
  L();

  L(`## Next 30-Day Experiment Plan`);
  r.report.experiments.forEach((e, i) => {
    L(`**${i + 1}. ${e.experiment}**`);
    L(`- Why: ${e.why}`);
    L(`- How to measure: ${e.how_to_measure}`);
    L(`- Success looks like: ${e.success_looks_like}`);
    L();
  });

  L(`## Data Limitations`);
  for (const b of r.report.data_limitations) L(`- ${b}`);
  L();
  L(`---`);
  L(
    `_Generated by Success Signal Analysis · successsignals.optimizationdoc.com · Recommendations are experiments, not guarantees._`,
  );

  return lines.join("\n");
}
