// Branded HTML version of the report for the emailed copy. Inline styles only
// (email clients strip <style>), OpDoc palette, single-column, mobile-friendly.

import type { AnalysisResult } from "./types";

const INK = "#15243D";
const INK3 = "#4F5E78";
const BOLT = "#2A6FDB";
const PAPER = "#FAF6E9";
const BORDER = "#E2DAB9";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

const h2 = (t: string) =>
  `<h2 style="font-family:Arial,sans-serif;font-size:20px;color:${INK};margin:28px 0 8px;">${esc(t)}</h2>`;
const li = (t: string) =>
  `<li style="font-family:Arial,sans-serif;font-size:15px;color:${INK};line-height:1.5;margin:4px 0;">${esc(t)}</li>`;
const ul = (items: string[]) =>
  `<ul style="margin:6px 0 6px 18px;padding:0;">${items.map(li).join("")}</ul>`;

export function renderReportHtml(r: AnalysisResult): string {
  const parts: string[] = [];
  parts.push(
    `<div style="background:${PAPER};padding:24px;">
     <div style="max-width:640px;margin:0 auto;background:#fff;border:1px solid ${BORDER};border-radius:12px;padding:28px;">
     <div style="font-family:Arial,sans-serif;font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:${INK3};">Success Signal Analysis</div>
     <h1 style="font-family:Arial,sans-serif;font-size:26px;color:${INK};margin:6px 0 4px;">Find the signal in your campaigns</h1>
     <div style="font-family:Arial,sans-serif;font-size:13px;color:${INK3};">${esc(r.account.name)} · ${r.campaigns.length} campaigns · scored by ${esc(r.scoreMethod)}</div>`,
  );

  parts.push(h2("Executive Summary"));
  parts.push(ul(r.report.executive_summary));

  parts.push(h2("Success Signals Detected"));
  for (const s of r.report.signals) {
    parts.push(
      `<div style="border-left:3px solid ${BOLT};padding:4px 0 4px 14px;margin:14px 0;">
        <div style="font-family:Arial,sans-serif;font-size:16px;font-weight:bold;color:${INK};">${esc(s.name)} <span style="font-size:12px;color:${INK3};font-weight:normal;">· ${esc(s.confidence)} confidence</span></div>
        ${ul(s.evidence)}
        <div style="font-family:Arial,sans-serif;font-size:14px;color:${INK};margin-top:6px;"><em>${esc(s.related_principle)}</em></div>
        <div style="font-family:Arial,sans-serif;font-size:14px;color:${INK};margin-top:6px;"><strong>Try:</strong> ${esc(s.recommended_experiment)}</div>
      </div>`,
    );
  }

  parts.push(h2("What To Repeat"));
  parts.push(ul(r.report.what_to_repeat));
  parts.push(h2("What To Stop Doing"));
  parts.push(ul(r.report.what_to_stop));

  parts.push(h2("Next 30-Day Experiment Plan"));
  parts.push(
    ul(
      r.report.experiments.map(
        (e) => `${e.experiment} — measure: ${e.how_to_measure}`,
      ),
    ),
  );

  parts.push(h2("Data Limitations"));
  parts.push(ul(r.report.data_limitations));

  parts.push(
    `<hr style="border:none;border-top:1px solid ${BORDER};margin:24px 0;">
     <div style="font-family:Arial,sans-serif;font-size:12px;color:${INK3};">Generated by Success Signal Analysis · <a href="https://successsignals.optimizationdoc.com" style="color:${BOLT};">successsignals.optimizationdoc.com</a>. Recommendations are experiments, not guarantees.</div>
     </div></div>`,
  );

  return parts.join("\n");
}
